version: "3"
services:
  db-users:
    image: postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: ai_tem_de_mudar_isso_aqui
  db-products:
    image: postgres
    environment:
      POSTGRES_DB: products
      POSTGRES_PASSWORD: ai_tem_de_mudar_isso_aqui
  api-discounts:
    depends_on:
      - "db-users"
      - "db-products"
    build:
      context: .
      dockerfile: apps/discounts/Dockerfile
    ports:
      - "50051:50051"
    environment:
      ENV_NAME: "docker"
